services:
  - type: web
    name: xp-agent
    env: python
    plan: free
    region: singapore  # change to 'singapore' or 'frankfurt' if closer to you
    buildCommand: pip install -r requirements.txt
    startCommand: python xp_agent.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000  # Render will auto-inject PORT; this is just fallback
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_TASK_DATABASE_ID
        sync: false
      - key: NOTION_XP_LEDGER_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true




#calendar agent
services:
  - type: web
    name: calendar_agent
    env: python
    plan: free
    region: singapore

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT calendar_agent:app

    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        value: "/etc/secrets/google_service_key.json"
      - key: GROQ_API_KEY
        sync: false

    secretFiles:
      - name: google_service_key.json
        path: /etc/secrets/google_service_key.json









#email agent
services:
  - type: web
    name: email-agent
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT email_agent:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        value: pos-agent@mvp.com





#research agent
services:
  - type: web
    name: research-agent
    env: python
    plan: free
    region: singapore

    buildCommand: |
      pip install -r requirements.txt

    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT research_agent:app

    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

