services:
  # ------------------ XP Agent ------------------
  - type: web
    name: xp-agent
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT xp_agent:app
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_TASK_DATABASE_ID
        sync: false
      - key: NOTION_XP_LEDGER_ID
        sync: false
      - key: XP_AGENT_PORT
        value: "10001"




#calender 
services:
  - type: web
    name: calendar-agent
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT calendar_agent:app
    envVars:
      - key: GOOGLE_CALENDAR_ID
        value: "aayushnarwade10@gmail.com"
      - key: GOOGLE_CREDENTIALS_PATH
        value: "/etc/secrets/google_service_key.json"
      - key: GROQ_API_KEY
        sync: false
    secretFiles:
      - name: google_service_key.json
        path: /etc/secrets/google_service_key.json





#email agent
services:
  - type: web
    name: email-agent
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT email_agent:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        value: pos-agent@mvp.com
